version: "3.9"

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service1
      - service2
    networks:
      - backend

  service1:
    build: ./service_1
    networks:
      - backend

  service2:
    build: ./service_2
    networks:
      - backend

networks:
  backend:
    driver: bridge

